In [1]:
import numpy as np

In [2]:
first_pattern = np.array([[1, 1, -1, 1],
                          [-1, -1, 1, -1],
                          [-1, -1, 1, -1],
                          [1, 1, -1, 1]])
second_pattern = np.array([[1, 1, -1, 1],
                           [-1, -1, 1, -1],
                           [-1, 1, -1, 1],
                           [1, -1, -1, 1]])
third_pattern = np.array([[-1, 1, 1, -1],
                          [-1, -1, 1, 1],
                          [-1, 1, -1, 1],
                          [1, -1, -1, -1]])

In [3]:
first_pattern_flattened = first_pattern.flatten()
second_pattern_flattened = second_pattern.flatten()
third_pattern_flattened = third_pattern.flatten()

In [4]:
print("first_pattern_flattened =", first_pattern_flattened)
print("second_pattern_flattened =", second_pattern_flattened)
print("third_pattern_flattened =", third_pattern_flattened)

first_pattern_flattened = [ 1  1 -1  1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1]
second_pattern_flattened = [ 1  1 -1  1 -1 -1  1 -1 -1  1 -1  1  1 -1 -1  1]
third_pattern_flattened = [-1  1  1 -1 -1 -1  1  1 -1  1 -1  1  1 -1 -1 -1]


In [5]:
my_patterns = np.array([first_pattern_flattened, second_pattern_flattened, third_pattern_flattened])

In [6]:
def hopfield_weight(patterns):
  N = patterns.shape[1]
  weight = np.zeros((N, N))
  for i in range(N):
    for j in range(N):
      if i==j:
            weight[i, j] = 0
      else:
        for pattern in patterns:
            weight[i, j] += np.sum((pattern[i] * pattern[j]))
  #weight /= N
  return weight

In [7]:
my_weight = hopfield_weight(my_patterns)
print(my_weight)

[[ 0.  1. -3.  3. -1. -1.  1. -3. -1. -1.  1. -1.  1.  1. -1.  3.]
 [ 1.  0. -1.  1. -3. -3.  3. -1. -3.  1. -1.  1.  3. -1. -3.  1.]
 [-3. -1.  0. -3.  1.  1. -1.  3.  1.  1. -1.  1. -1. -1.  1. -3.]
 [ 3.  1. -3.  0. -1. -1.  1. -3. -1. -1.  1. -1.  1.  1. -1.  3.]
 [-1. -3.  1. -1.  0.  3. -3.  1.  3. -1.  1. -1. -3.  1.  3. -1.]
 [-1. -3.  1. -1.  3.  0. -3.  1.  3. -1.  1. -1. -3.  1.  3. -1.]
 [ 1.  3. -1.  1. -3. -3.  0. -1. -3.  1. -1.  1.  3. -1. -3.  1.]
 [-3. -1.  3. -3.  1.  1. -1.  0.  1.  1. -1.  1. -1. -1.  1. -3.]
 [-1. -3.  1. -1.  3.  3. -3.  1.  0. -1.  1. -1. -3.  1.  3. -1.]
 [-1.  1.  1. -1. -1. -1.  1.  1. -1.  0. -3.  3.  1. -3. -1. -1.]
 [ 1. -1. -1.  1.  1.  1. -1. -1.  1. -3.  0. -3. -1.  3.  1.  1.]
 [-1.  1.  1. -1. -1. -1.  1.  1. -1.  3. -3.  0.  1. -3. -1. -1.]
 [ 1.  3. -1.  1. -3. -3.  3. -1. -3.  1. -1.  1.  0. -1. -3.  1.]
 [ 1. -1. -1.  1.  1.  1. -1. -1.  1. -3.  3. -3. -1.  0.  1.  1.]
 [-1. -3.  1. -1.  3.  3. -3.  1.  3. -1.  1. -1. -3.  1.  0. 

In [8]:
N = my_patterns.shape[1]
my_scaled_weight = hopfield_weight(my_patterns) / N
print(my_scaled_weight)

[[ 0.      0.0625 -0.1875  0.1875 -0.0625 -0.0625  0.0625 -0.1875 -0.0625
  -0.0625  0.0625 -0.0625  0.0625  0.0625 -0.0625  0.1875]
 [ 0.0625  0.     -0.0625  0.0625 -0.1875 -0.1875  0.1875 -0.0625 -0.1875
   0.0625 -0.0625  0.0625  0.1875 -0.0625 -0.1875  0.0625]
 [-0.1875 -0.0625  0.     -0.1875  0.0625  0.0625 -0.0625  0.1875  0.0625
   0.0625 -0.0625  0.0625 -0.0625 -0.0625  0.0625 -0.1875]
 [ 0.1875  0.0625 -0.1875  0.     -0.0625 -0.0625  0.0625 -0.1875 -0.0625
  -0.0625  0.0625 -0.0625  0.0625  0.0625 -0.0625  0.1875]
 [-0.0625 -0.1875  0.0625 -0.0625  0.      0.1875 -0.1875  0.0625  0.1875
  -0.0625  0.0625 -0.0625 -0.1875  0.0625  0.1875 -0.0625]
 [-0.0625 -0.1875  0.0625 -0.0625  0.1875  0.     -0.1875  0.0625  0.1875
  -0.0625  0.0625 -0.0625 -0.1875  0.0625  0.1875 -0.0625]
 [ 0.0625  0.1875 -0.0625  0.0625 -0.1875 -0.1875  0.     -0.0625 -0.1875
   0.0625 -0.0625  0.0625  0.1875 -0.0625 -0.1875  0.0625]
 [-0.1875 -0.0625  0.1875 -0.1875  0.0625  0.0625 -0.0625  0.      0.

In [84]:
test_pattern = np.array([[1, -1, 1, 1],
                         [-1, -1, 1, -1],
                         [1, 1, -1, -1],
                         [1, -1, -1, 1]])
test_pattern_flattened = test_pattern.flatten()
print(test_pattern_flattened)

[ 1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1 -1 -1  1]


In [114]:
def update(pattern, weight):
  updated_pattern = pattern.copy()
  for i in range(len(updated_pattern)):
    updated_pattern[i] = np.sign(np.dot(weight[i], updated_pattern.T))
  
  updated_pattern = np.int64(updated_pattern)
  return updated_pattern

In [115]:
update(test_pattern_flattened, my_scaled_weight)

array([ 1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1])

In [117]:
i = 0
updated_pattern = test_pattern_flattened
while(i < 10):
  i += 1
  updated_pattern = update(updated_pattern, my_scaled_weight)
  print(updated_pattern)
  if (first_pattern_flattened == updated_pattern).all():
    print("Round:" + str(i))
    print("First pattern is predictable, because has minimum energy.")
    break
  if (second_pattern_flattened == updated_pattern).all():
    print("Round:" + str(i))
    print("Second pattern is predictable, because has minimum energy.")
    break
  if (third_pattern_flattened == updated_pattern).all():
    print("Round:" + str(i))
    print("Third pattern is predictable, because has minimum energy.")
    break

[ 1  1 -1  1 -1 -1  1 -1 -1  1 -1  1  1 -1 -1  1]
Round:1
Second pattern is predictable, because has minimum energy.


After first round, we reach second pattern that has minimum energy.

In [121]:
first_pattern_energy = - 0.5 * np.dot(np.dot(first_pattern_flattened.T, my_scaled_weight), first_pattern_flattened)
print("First pattern energy =", first_pattern_energy)

First pattern energy = -8.625


In [122]:
second_pattern_energy = - 0.5 * np.dot(np.dot(second_pattern_flattened.T, my_scaled_weight), second_pattern_flattened)
print("Second pattern energy =", second_pattern_energy)

Second pattern energy = -9.625


In [123]:
third_pattern_energy = - 0.5 * np.dot(np.dot(third_pattern_flattened.T, my_scaled_weight), third_pattern_flattened)
print("Third pattern energy =", third_pattern_energy)

Third pattern energy = -7.75
